AI팀메이트/ai_teammate/ai_teammate/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('users/', include('users.urls')),
    path('edit/', include('edit.urls')),
    path('alarm/', include('alarm.urls')),
    path('team_rec/', include('team_rec.urls')),
    path('study_rec/', include('study_rec.urls')),
    path('newsletter/',include('newsletter.urls')),
]

AI팀메이트/ai_teammate/edit/urls.py
from django.urls import path
from . import views

app_name = "edit"
urlpatterns = [
    path("info_edit/<int:customer_pk>", views.info_edit, name="info_edit"),  # 정보수정하기
    path(
        "domain_edit/<int:customer_pk>", views.domain_edit, name="domain_edit"
    ),  # 흥미 설문조사 정보수정
    path(
        "score_edit/<int:customer_pk>", views.score_edit, name="score_edit"
    ),  # 실력 설문조사 정보수정
    path(
        "role_edit/<int:customer_pk>", views.role_edit, name="role_edit"
    ),  # 흥미 설문조사 정보수정
    path(
        "study_edit/<int:customer_pk>", views.study_edit, name="study_edit"
    ),  # 흥미 설문조사 정보수정
]

AI팀메이트/ai_teammate/edit/models.py
from django.db import models

# Create your models here.

AI팀메이트/ai_teammate/edit/views.py
from django.shortcuts import render, redirect
from users.models import Customer, Domain, Score, Role, Study
from django.contrib.auth.models import User
from django.contrib import auth

# 정보수정
def info_edit(request, customer_pk):
    if request.method == "POST":
        Customer.objects.filter(pk=customer_pk).update(
            name=request.POST["name"],
            email=request.POST["email"],
            phone_num=request.POST["phone_num"],
            team_state=request.POST["team_check"],
            study_state=request.POST["study_check"],
            intro=request.POST["intro"],
        )

        return redirect("home")

    customer = Customer.objects.get(pk=customer_pk)

    context = {"customer": customer}

    return render(request, "edit/info_edit.html", context)


# 정보수정시 오류방지 MSG
ERROR_MSG2 = {
    "error": "10개의 하트를 제대로 베팅하지않으셨습니다. 값을 다시확인해주세요!!",
    "error2": "null값이 존재합니다. 입력값을 다시 한번 확인해주세요!!!",
}

# 설문조사정보수정
def domain_edit(request, customer_pk):

    customer = Customer.objects.get(pk=customer_pk)
    domain = Domain.objects.get(foreignkey=customer)

    context = {
        "error": {"state": False, "msg": ""},
        "customer": customer,
        "domain": domain,
        "left_heart": 10 - domain.domain_sum,
    }

    if request.method == "POST":

        health = request.POST["health"]
        economy = request.POST["economy"]
        culture_art = request.POST["culture_art"]
        education = request.POST["education"]
        society = request.POST["society"]
        technology = request.POST["technology"]

        if (
            len(health)
            and len(economy)
            and len(culture_art)
            and len(education)
            and len(society)
            and len(technology)
        ):
            if (
                int(health)
                + int(economy)
                + int(culture_art)
                + int(education)
                + int(society)
                + int(technology)
                == 10
            ):

                Domain.objects.filter(foreignkey=customer).update(
                    health=request.POST["health"],
                    economy=request.POST["economy"],
                    culture_art=request.POST["culture_art"],
                    education=request.POST["education"],
                    society=request.POST["society"],
                    technology=request.POST["technology"],
                    domain_sum=int(health)
                    + int(economy)
                    + int(culture_art)
                    + int(education)
                    + int(society)
                    + int(technology),
                )

                return redirect("home")

            else:
                context["error"]["state"] = True
                context["error"]["msg"] = ERROR_MSG2["error"]
        else:
            context["error"]["state"] = True
            context["error"]["msg"] = ERROR_MSG2["error2"]

    return render(request, "edit/domain_edit.html", context)


# 설문조사정보수정
def score_edit(request, customer_pk):

    customer = Customer.objects.get(pk=customer_pk)
    score = Score.objects.get(foreignkey=customer)

    context = {
        "error": {"state": False, "msg": ""},
        "customer": customer,
        "score": score,
    }

    if request.method == "POST":
        web = request.POST["web"]
        design = request.POST["design"]
        machine_learning = request.POST["machine_learning"]
        statistics = request.POST["statistics"]
        deep_learning = request.POST["deep_learning"]
        algorithm = request.POST["algorithm"]
        nlp = request.POST["nlp"]

        if (
            len(web)
            and len(design)
            and len(machine_learning)
            and len(statistics)
            and len(deep_learning)
            and len(algorithm)
            and len(nlp)
        ):
            web = round(float(web))
            design = round(float(design))
            machine_learning = round(float(machine_learning))
            statistics = round(float(statistics))
            deep_learning = round(float(deep_learning))
            algorithm = round(float(algorithm))
            nlp = round(float(nlp))
            data_score = round(int(statistics) * 0.5 + int(machine_learning) * 0.5)
            modeling_score = round(
                int(machine_learning) * 0.25
                + int(deep_learning) * 0.25
                + int(algorithm) * 0.25
                + int(nlp) * 0.25
            )

            Score.objects.filter(foreignkey=customer).update(
                web=web,
                design=design,
                machine_learning=machine_learning,
                statistics=statistics,
                deep_learning=deep_learning,
                algorithm=algorithm,
                nlp=nlp,
                data_score=data_score,
                modeling_score=modeling_score,
                score_sum=int(web)
                + int(design)
                + int(machine_learning)
                + int(statistics)
                + int(deep_learning)
                + int(algorithm)
                + int(nlp)
                + int(data_score)
                + int(modeling_score),
            )

            return redirect("home")

        else:
            context["error"]["state"] = True
            context["error"]["msg"] = ERROR_MSG2["error2"]

    return render(request, "edit/score_edit.html", context)


# 설문조사정보수정
def role_edit(request, customer_pk):

    customer = Customer.objects.get(pk=customer_pk)
    role = Role.objects.get(foreignkey=customer)

    context = {
        "error": {"state": False, "msg": ""},
        "customer": customer,
        "role": role,
        "left_heart": 10 - role.role_sum,
    }

    if request.method == "POST":
        analysis_hearts = request.POST["analysis_hearts"]
        web_hearts = request.POST["web_hearts"]
        design_hearts = request.POST["design_hearts"]
        modeling_hearts = request.POST["modeling_hearts"]

        if (
            len(analysis_hearts)
            and len(web_hearts)
            and len(design_hearts)
            and len(modeling_hearts)
        ):
            if (
                int(analysis_hearts)
                + int(web_hearts)
                + int(design_hearts)
                + int(modeling_hearts)
                == 10
            ):

                Role.objects.filter(foreignkey=customer).update(
                    analysis_hearts=request.POST["analysis_hearts"],
                    web_hearts=request.POST["web_hearts"],
                    design_hearts=request.POST["design_hearts"],
                    modeling_hearts=request.POST["modeling_hearts"],
                    role_sum=int(analysis_hearts)
                    + int(web_hearts)
                    + int(design_hearts)
                    + int(modeling_hearts),
                )

                return redirect("home")
            else:
                context["error"]["state"] = True
                context["error"]["msg"] = ERROR_MSG2["error"]
        else:
            context["error"]["state"] = True
            context["error"]["msg"] = ERROR_MSG2["error2"]

    return render(request, "edit/role_edit.html", context)


# 설문조사정보수정
def study_edit(request, customer_pk):

    customer = Customer.objects.get(pk=customer_pk)
    study = Study.objects.get(foreignkey=customer)
    context = {
        "error": {"state": False, "msg": ""},
        "customer": customer,
        "study": study,
        "left_heart": 10 - study.study_sum,
    }

    if request.method == "POST":
        web_hearts = request.POST["web_hearts"]
        design_hearts = request.POST["design_hearts"]
        machine_learning_hearts = request.POST["machine_learning_hearts"]
        statistics_hearts = request.POST["statistics_hearts"]
        deep_learning_hearts = request.POST["deep_learning_hearts"]
        algorithm_hearts = request.POST["algorithm_hearts"]
        nlp_hearts = request.POST["nlp_hearts"]
        basic_python_hearts = request.POST["basic_python_hearts"]
        data_analysis_hearts = request.POST["data_analysis_hearts"]
        voice_recog_hearts = request.POST["voice_recog_hearts"]
        computer_vision_hearts = request.POST["computer_vision_hearts"]
        rec_system_hearts = request.POST["rec_system_hearts"]
        reinforcement_hearts = request.POST["reinforcement_hearts"]
        if (
            len(web_hearts)
            and len(design_hearts)
            and len(machine_learning_hearts)
            and len(statistics_hearts)
            and len(deep_learning_hearts)
            and len(algorithm_hearts)
            and len(nlp_hearts)
            and len(basic_python_hearts)
            and len(data_analysis_hearts)
            and len(voice_recog_hearts)
            and len(computer_vision_hearts)
            and len(rec_system_hearts)
            and len(reinforcement_hearts)
        ):
            if (
                int(web_hearts)
                + int(design_hearts)
                + int(machine_learning_hearts)
                + int(statistics_hearts)
                + int(deep_learning_hearts)
                + int(algorithm_hearts)
                + int(nlp_hearts)
                + int(basic_python_hearts)
                + int(data_analysis_hearts)
                + int(voice_recog_hearts)
                + int(computer_vision_hearts)
                + int(rec_system_hearts)
                + int(reinforcement_hearts)
                == 10
            ):

                Study.objects.filter(foreignkey=customer).update(
                    web_hearts=web_hearts,
                    design_hearts=design_hearts,
                    machine_learning_hearts=machine_learning_hearts,
                    statistics_hearts=statistics_hearts,
                    deep_learning_hearts=deep_learning_hearts,
                    algorithm_hearts=algorithm_hearts,
                    nlp_hearts=nlp_hearts,

AI팀메이트/ai_teammate/edit/templates/edit/domain_edit.html
{% extends "base.html" %}

{% block title %}
<title>설문정보 수정</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
<link rel='stylesheet' href='{% static 'edit.css' %}'/>
<link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel='stylesheet' type='text/css'>

<script type='text/javascript'>
    function setheart(id, value) {
        var el1 = document.getElementById('hearts');
        var el2 = document.getElementById(id);

        var hearts = Number(el1.textContent);
        var select = Number(el2.value);
        
        if (value < 0) {
            if ((select + value >= 0)) {
                el1.innerHTML = hearts - value;
                el2.value = select + value;
            }
        }
        if (value > 0) {
            if (hearts - value >= 0) {
                el1.innerHTML = hearts - value;
                el2.value = select + value;
            }
        }
    }
</script>

<style>

    /* .form_input {
        margin-top: 3%;
        margin-bottom: 3%;
    } */
    .form_button {
        margin-top: 6%;
        margin-bottom: 20%;
    }

    #line_type_A { width: 90%; margin-bottom: 5%; margin-top: 3%;}

    #right_title {
        margin-top: 20%;
        
        width: 90%;
        
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        /* background-color: red; */
    }
    #right_title > h2 { font-size: 30px; font-weight: bold;}
    #right_title > img { width: 35px; margin-left: 40px; margin-right: 10px;}

    .form_value {
        width: 90%;
        height: 90px;
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
    }
    .form_value > h4 { font-size: 20px; font-weight: bold;}
    .button_square { width: 90% }
    .value {
        width: 45px;
        height: 27px;
        font-size: 23px;
        border-radius: 0px;
        text-align: center;
        background-color: white;
    }
    .bttn {
        height: 30px;
        width: 30px;
        font-size: 20px;
        font-weight: bold;
    }

</style>
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
<div id="main">
    <div id="header">
        <h1><a href='{% url 'home' %}'>TeamMate</a></h1>

        <div>
            <a href='{% url 'edit:info_edit' user.customer.pk %}'>개인정보</a>
            <a href='{% url 'edit:role_edit' user.customer.pk %}'>역할</a>
            <a href='{% url 'edit:score_edit' user.customer.pk %}'>실력</a>
            <a href='{% url 'edit:domain_edit' user.customer.pk %}'>흥미</a>
            <a href='{% url 'edit:study_edit' user.customer.pk %}'>스터디</a>
            <a href='{% url 'home' %}'>home</a>
        </div>
    </div>
    <div id="err">
        {% if error.state %}
        <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
        <strong>{{ error.msg }}</strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {%endif%}
    </div>
    <div id="article">
        <div id="right">
            
            <div id='right_title'>
                <h2>관심분야 배팅 수정</h2>
                <img src='{% static 'heart.png' %}' />
                <h2 id='hearts'>{{left_heart}}</h2>
            </div>
            <img id='line_type_A' src='{% static 'line_type_A.png' %}' />
            
            <form action="{% url 'edit:domain_edit' customer.pk %}" method = 'POST'>
            {% csrf_token %}
                <div class='form_value'>
                    <h4>건강 (스포츠, 헬스, 의료)</h4>
                    <!-- <h4>건강</h4> -->
                    <div>
                        <input class='bttn' type='button' onclick='setheart("health", -1)' value='-'/>
                        <input class='value' id='health' type='number' name='health' value='{{domain.health}}' readonly/>
                        <input class='bttn' type='button' onclick='setheart("health", 1)' value='+'/>
                    </div>
                </div>
                
                <div class='form_value'>
                    <h4>경제 (금융, 부동산, 비즈니스)</h4>
                    <!-- <h4>경제</h4> -->
                    <div>
                        <input class='bttn' type='button' onclick='setheart("economy", -1)' value='-'/>
                        <input class='value' id='economy' type='number' name='economy' value='{{domain.economy}}' readonly/>
                        <input class='bttn' type='button' onclick='setheart("economy", 1)' value='+'/>
                    </div>
                </div>
                
                <div class='form_value'>
                    <h4>문화/예술 (음악, 영화,  게임, 패션/뷰티,  디자인)</h4>
                    <!-- <h4>문화/예술</h4> -->
                    <div>
                        <input class='bttn' type='button' onclick='setheart("culture_art", -1)' value='-'/>
                        <input class='value' id='culture_art' type='number' name='culture_art' value='{{domain.culture_art}}' readonly/>
                        <input class='bttn' type='button' onclick='setheart("culture_art", 1)' value='+'/>
                    </div>
                </div>

                <div class='form_value'>
                    <h4>교육 (도서, 학습)</h4>
                    <!-- <h4>교육</h4> -->
                    <div>
                        <input class='bttn' type='button' onclick='setheart("education", -1)' value='-'/>
                        <input class='value' id='education' type='number' name='education' value='{{domain.education}}' readonly/>
                        <input class='bttn' type='button' onclick='setheart("education", 1)' value='+'/>
                    </div>
                </div>
                <div class='form_value'>
                    <h4>사회 (연애, 소셜, 여행, 교통, 뉴스)</h4>
                    <!-- <h4>사회</h4> -->
                    <div>
                        <input class='bttn' type='button' onclick='setheart("society", -1)' value='-'/>
                        <input class='value' id='society' type='number' name='society' value='{{domain.society}}' readonly/>
                        <input class='bttn' type='button' onclick='setheart("society", 1)' value='+'/>
                    </div>
                </div>
                
                <div class='form_value'>
                    <h4>기술 (자연, 화학, 공학)</h4>
                    <!-- <h4>기술</h4> -->
                    <div>
                        <input class='bttn' type='button' onclick='setheart("technology", -1)' value='-'/>
                        <input class='value' id='technology' type='number' name='technology' value='{{domain.technology}}' readonly/>
                        <input class='bttn' type='button' onclick='setheart("technology", 1)' value='+'/>
                    </div>
                </div>    

                <div class='form_button'>
                    <!-- <form action="{% url 'home' %}">
                        <button class='button_square' type="submit">홈</button>
                    </form> -->
                    <button class='button_square' type="submit">수정하기</button>
                </div>
            </form>
        </div>
        <div id="left">
            <img src='{% static 'info_edit.png' %}' />
        </div>
    </div>
</div>
{% endblock %}

AI팀메이트/ai_teammate/edit/templates/edit/role_edit.html
{% extends "base.html" %}

{% block title %}
<title>설문정보 수정</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
<link rel='stylesheet' href='{% static 'edit.css' %}'/>
<link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel='stylesheet' type='text/css'>

<script type='text/javascript'>
    function setheart(id, value) {
        var el1 = document.getElementById('hearts');
        var el2 = document.getElementById(id);

        var hearts = Number(el1.textContent);
        var select = Number(el2.value);
        
        if (value < 0) {
            if ((select + value >= 0)) {
                el1.innerHTML = hearts - value;
                el2.value = select + value;
            }
        }
        if (value > 0) {
            if (hearts - value >= 0) {
                el1.innerHTML = hearts - value;
                el2.value = select + value;
            }
        }
    }
</script>

<style>

    /* .form_input {
        margin-top: 3%;
        margin-bottom: 3%;
    } */
    .form_button {
        margin-top: 6%;
        margin-bottom: 20%;
    }

    #line_type_A { width: 90%; margin-bottom: 5%; margin-top: 3%;}

    #right_title {
        margin-top: 20%;

        width: 90%;
        
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        /* background-color: red; */
    }
    #right_title > h2 { font-size: 30px; font-weight: bold; }
    #right_title > img { width: 35px; margin-left: 40px; margin-right: 10px;}

    .form_value {
        width: 90%;
        height: 90px;
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
    }
    .form_value > h4 { font-size: 20px; font-weight: bold;}
    .button_square { width: 90% }
    .value {
        width: 45px;
        height: 27px;
        font-size: 23px;
        border-radius: 0px;
        text-align: center;
        background-color: white;
    }
    .bttn {
        height: 30px;
        width: 30px;
        font-size: 20px;
        font-weight: bold;
    }

</style>
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
    <div id="main">
        <div id="header">
            <h1><a href='{% url 'home' %}'>TeamMate</a></h1>

            <div>
                <a href='{% url 'edit:info_edit' user.customer.pk %}'>개인정보</a>
                <a href='{% url 'edit:role_edit' user.customer.pk %}'>역할</a>
                <a href='{% url 'edit:score_edit' user.customer.pk %}'>실력</a>
                <a href='{% url 'edit:domain_edit' user.customer.pk %}'>흥미</a>
                <a href='{% url 'edit:study_edit' user.customer.pk %}'>스터디</a>
                <a href='{% url 'home' %}'>home</a>
            </div>
        </div>
        <div id="err">
            {% if error.state %}
            <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
            <strong>{{ error.msg }}</strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {%endif%}
        </div>
        <div id="article">
            <div id="right">
                
                <div id='right_title'>
                    <h2>역할 배팅 수정</h2>
                    <img src='{% static 'heart.png' %}' />
                    <h2 id='hearts'>{{left_heart}}</h2>
                </div>
                <img id='line_type_A' src='{% static 'line_type_A.png' %}' />
                
                <form action="{% url 'edit:role_edit' customer.pk %}" method = 'POST'>
                {% csrf_token %}
                    <div class='form_value'>
                        <h4>데이터분석</h4>
                        <div>
                            <input class='bttn' type='button' onclick='setheart("analysis_hearts", -1)' value='-'/>
                            <input class='value' id='analysis_hearts' type='number' name='analysis_hearts' value='{{role.analysis_hearts}}' readonly/>
                            <input class='bttn' type='button' onclick='setheart("analysis_hearts", 1)' value='+'/>
                        </div>
                    </div>
                    
                    <div class='form_value'>
                        <h4>웹</h4>
                        <div>
                            <input class='bttn' type='button' onclick='setheart("web_hearts", -1)' value='-'/>
                            <input class='value' id='web_hearts' type='number' name='web_hearts' value='{{role.web_hearts}}' readonly/>
                            <input class='bttn' type='button' onclick='setheart("web_hearts", 1)' value='+'/>
                        </div>
                    </div>
                
                    <div class='form_value'>
                        <h4>디자인</h4>
                        <div>
                            <input class='bttn' type='button' onclick='setheart("design_hearts", -1)' value='-'/>
                            <input class='value' id='design_hearts' type='number' name='design_hearts' value='{{role.design_hearts}}' readonly/>
                            <input class='bttn' type='button' onclick='setheart("design_hearts", 1)' value='+'/>
                        </div>
                    </div>

                    <div class='form_value'>
                        <h4>모델링</h4>
                        <div>
                            <input class='bttn' type='button' onclick='setheart("modeling_hearts", -1)' value='-'/>
                            <input class='value' id='modeling_hearts' type='number' name='modeling_hearts' value='{{role.modeling_hearts}}' readonly/>
                            <input class='bttn' type='button' onclick='setheart("modeling_hearts", 1)' value='+'/>
                        </div>
                    </div>

                    <div class='form_button'>
                        <!-- <form action="{% url 'home' %}">
                            <button class='button_square' type="submit">홈</button>
                        </form> -->
                        <button class='button_square' type="submit">수정하기</button>
                    </div>
                </form>
            </div>
            <div id="left">
                <img src='{% static 'info_edit.png' %}' />
            </div>
        </div>
    </div>
{% endblock %}