AI팀메이트/ai_teammate/ai_teammate/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('users/', include('users.urls')),
    path('edit/', include('edit.urls')),
    path('alarm/', include('alarm.urls')),
    path('team_rec/', include('team_rec.urls')),
    path('study_rec/', include('study_rec.urls')),
    path('newsletter/',include('newsletter.urls')),
]

AI팀메이트/ai_teammate/edit/urls.py
from django.urls import path
from . import views

app_name = "edit"
urlpatterns = [
    path("info_edit/<int:customer_pk>", views.info_edit, name="info_edit"),  # 정보수정하기
    path(
        "domain_edit/<int:customer_pk>", views.domain_edit, name="domain_edit"
    ),  # 흥미 설문조사 정보수정
    path(
        "score_edit/<int:customer_pk>", views.score_edit, name="score_edit"
    ),  # 실력 설문조사 정보수정
    path(
        "role_edit/<int:customer_pk>", views.role_edit, name="role_edit"
    ),  # 흥미 설문조사 정보수정
    path(
        "study_edit/<int:customer_pk>", views.study_edit, name="study_edit"
    ),  # 흥미 설문조사 정보수정
]

AI팀메이트/ai_teammate/newsletter/urls.py
from django.urls import path
from . import views


app_name = "newsletter"
urlpatterns = [
    path("art", views.news_art_list, name="art"),
    path("economy", views.news_economy_list, name="economy"),
    path("social", views.news_social_list, name="social"),
    path("health", views.news_health_list, name="health"),
    path("tech", views.news_tech_list, name="tech"),
    path("all", views.news_all_list, name="all"),
]

AI팀메이트/ai_teammate/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("signup2/<int:customer_pk>", views.signup2, name="signup2"),
    path("signup3/<int:customer_pk>", views.signup3, name="signup3"),
    path("signup4/<int:customer_pk>", views.signup4, name="signup4"),
    path("signup5/<int:customer_pk>", views.signup5, name="signup5"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

AI팀메이트/ai_teammate/newsletter/models.py
from django.db import models

# Create your models here.
class News(models.Model) :
    link = models.TextField()
    title = models.TextField()
    date = models.TextField()
    content = models.TextField()
    tag = models.TextField()
    big_category = models.TextField()
    category = models.TextField()
    team_category = models.TextField()

AI팀메이트/ai_teammate/newsletter/views.py
from django.shortcuts import render
from django_pandas.io import read_frame
from users.models import Customer
from newsletter.models import News

# [ '공통','문화/예술', '경제', '건강', '사회', '기술']


def news_all_list(request):
    page = 10
    if request.method == "POST":
        page = int(request.POST["page"]) + 10

    news_data = News.objects.all()
    df0 = read_frame(news_data)

    news_data = df0.loc[
        :,
        [
            "link",
            "title",
            "date",
            "content",
            "tag",
            "team_category",
        ],
    ]

    news = news_data[news_data.team_category == "공통"]
    news.reset_index(drop=True, inplace=True)

    all_list = []
    if news.shape[0] < page:
        for i in range(page - news.shape[0]):
            all_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )
    else:
        for i in range(10):
            all_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )

    context = {"all_list": all_list, "page": page, "news_num": news.shape[0]}

    return render(request, "newsletter_all.html", context)


def news_art_list(request):
    page = 10
    if request.method == "POST":
        page = int(request.POST["page"]) + 10

    news_data = News.objects.all()
    df0 = read_frame(news_data)

    news_data = df0.loc[
        :,
        [
            "link",
            "title",
            "date",
            "content",
            "tag",
            "team_category",
        ],
    ]

    news = news_data[news_data.team_category == "문화/예술"]
    news.reset_index(drop=True, inplace=True)

    art_list = []
    if news.shape[0] < page:
        for i in range(page - news.shape[0]):
            art_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )
    else:
        for i in range(10):
            art_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )

    context = {"art_list": art_list, "page": page, "news_num": news.shape[0]}

    return render(request, "newsletter_art.html", context)


def news_economy_list(request):
    page = 10
    if request.method == "POST":
        page = int(request.POST["page"]) + 10
    news_data = News.objects.all()
    df0 = read_frame(news_data)

    news_data = df0.loc[
        :,
        [
            "link",
            "title",
            "date",
            "content",
            "tag",
            "team_category",
        ],
    ]

    news = news_data[news_data.team_category == "경제"]
    news.reset_index(drop=True, inplace=True)

    economy_list = []
    if news.shape[0] < page:
        for i in range(page - news.shape[0]):
            economy_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )
    else:
        for i in range(10):
            economy_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )
    context = {"economy_list": economy_list, "page": page, "news_num": news.shape[0]}

    return render(request, "newsletter_economy.html", context)


def news_health_list(request):
    page = 10
    if request.method == "POST":
        page = int(request.POST["page"]) + 10
    news_data = News.objects.all()
    df0 = read_frame(news_data)

    news_data = df0.loc[
        :,
        [
            "link",
            "title",
            "date",
            "content",
            "tag",
            "team_category",
        ],
    ]

    news = news_data[news_data.team_category == "건강"]
    news.reset_index(drop=True, inplace=True)

    health_list = []
    if news.shape[0] < page:
        for i in range(page - news.shape[0]):
            health_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )
    else:
        for i in range(10):
            health_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )

    context = {"health_list": health_list, "page": page, "news_num": news.shape[0]}

    return render(request, "newsletter_health.html", context)


def news_social_list(request):
    page = 10
    if request.method == "POST":
        page = int(request.POST["page"]) + 10
    news_data = News.objects.all()
    df0 = read_frame(news_data)

    news_data = df0.loc[
        :,
        [
            "link",
            "title",
            "date",
            "content",
            "tag",
            "team_category",
        ],
    ]

    news = news_data[news_data.team_category == "사회"]
    news.reset_index(drop=True, inplace=True)

    social_list = []
    if news.shape[0] < page:
        for i in range(page - news.shape[0]):
            social_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )
    else:
        for i in range(10):
            social_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )

    context = {"social_list": social_list, "page": page, "news_num": news.shape[0]}

    return render(request, "newsletter_social.html", context)


def news_tech_list(request):
    page = 10
    if request.method == "POST":
        page = int(request.POST["page"]) + 10
    news_data = News.objects.all()
    df0 = read_frame(news_data)

    news_data = df0.loc[
        :,
        [
            "link",
            "title",
            "date",
            "content",
            "tag",
            "team_category",
        ],
    ]

    news = news_data[news_data.team_category == "기술"]
    news.reset_index(drop=True, inplace=True)

    tech_list = []
    if news.shape[0] < page:
        for i in range(page - news.shape[0]):
            tech_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )
    else:
        for i in range(10):
            tech_list.append(
                {
                    "link": news["link"][page + i - 10],
                    "title": news["title"][page + i - 10],
                    "date": news["date"][page + i - 10],
                    "category": news["team_category"][page + i - 10],
                    "tag": news["tag"][page + i - 10],
                }
            )

    context = {"tech_list": tech_list, "page": page, "news_num": news.shape[0]}

    return render(request, "newsletter_tech.html", context)

AI팀메이트/ai_teammate/newsletter/templates/newsletter_all.html
{% extends "base.html" %}

{% block title %}
<title>뉴스레터 - 공통</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:all' %}" style="color:white;">공통</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:art' %}">문화/예술</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:economy' %}">경제</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:health' %}">건강</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:social' %}">사회</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:tech' %}">기술</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <table class="table">
    <thead class="table-light text-center">
      <tr>
        <th style="width: 10%" scope="col">카테고리</th>
        <th style="width: 30%" scope="col">뉴스 제목</th>
        <th style="width: 40%" scope="col">태그</th>
        <th style="width: 5%" scope="col">날짜</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for news in all_list %}
       <tr>
        {% comment %} <th class="align-middle" style="width: 20%" scope="row">{{forloop.counter}}</th> {% endcomment %}
        <td style="align-middle" style="width: 10%">{{news.category}}</td>
        <td class="align-middle" style="width: 30%"><a href = {{news.link}}>{{news.title}}</td>
        <td class="align-middle" style="width: 40%">{{news.tag}}</td>
        <td style="align-middle" style="width: 5%">{{news.date}}</td>


        {% comment %} <td class="align-middle" style="width: 20%">{{}}</td> {% endcomment %}
          {% comment %} <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal{{customer.pk}}">스터디메이트 요청</a> {% endcomment %}
        {% comment %} </td> {% endcomment %}
      </tr>       
      {% endfor %}
    </tbody>
  </table>

  {% if news_num > page %}
  <form action="{% url 'newsletter:all' %}" method = 'POST'>
  {% csrf_token %}
    <input type="hidden" value="{{page}}" name='page' readonly/>
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">더 보기 ({{all_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  </form>
  {% else %}
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">끝 페이지 ({{all_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  {% endif %}

{% endblock %}

AI팀메이트/ai_teammate/newsletter/templates/newsletter_art.html
{% extends "base.html" %}

{% block title %}
<title>뉴스레터 - 문화/예술</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:all' %}">공통</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:art' %}" style="color:white;">문화/예술</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:economy' %}">경제</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:health' %}">건강</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:social' %}">사회</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:tech' %}">기술</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <table class="table">
    <thead class="table-light text-center">
      <tr>
        <th style="width: 10%" scope="col">카테고리</th>
        <th style="width: 30%" scope="col">뉴스 제목</th>
        <th style="width: 40%" scope="col">태그</th>
        <th style="width: 5%" scope="col">날짜</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for news in art_list %}
       <tr>
        {% comment %} <th class="align-middle" style="width: 20%" scope="row">{{forloop.counter}}</th> {% endcomment %}
        <td style="align-middle" style="width: 10%">{{news.category}}</td>
        <td class="align-middle" style="width: 30%"><a href = {{news.link}}>{{news.title}}</td>
        <td class="align-middle" style="width: 40%">{{news.tag}}</td>
        <td style="align-middle" style="width: 5%">{{news.date}}</td>


        {% comment %} <td class="align-middle" style="width: 20%">{{}}</td> {% endcomment %}
          {% comment %} <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal{{customer.pk}}">스터디메이트 요청</a> {% endcomment %}
        {% comment %} </td> {% endcomment %}
      </tr>       
      {% endfor %}
    </tbody>
  </table>

  {% if news_num > page %}
  <form action="{% url 'newsletter:art' %}" method = 'POST'>
  {% csrf_token %}
    <input type="hidden" value="{{page}}" name='page' readonly/>
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">더 보기 ({{art_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  </form>
  {% else %}
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">끝 페이지 ({{art_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  {% endif %}

{% endblock %}

AI팀메이트/ai_teammate/newsletter/templates/newsletter_economy.html
{% extends "base.html" %}

{% block title %}
<title>뉴스레터 - 경제</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:all' %}">공통</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:art' %}">문화/예술</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:economy' %}" style="color:white;">경제</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:health' %}">건강</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:social' %}">사회</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:tech' %}">기술</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <table class="table">
    <thead class="table-light text-center">
      <tr>
        <th style="width: 10%" scope="col">카테고리</th>
        <th style="width: 30%" scope="col">뉴스 제목</th>
        <th style="width: 40%" scope="col">태그</th>
        <th style="width: 5%" scope="col">날짜</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for news in economy_list %}
       <tr>
        {% comment %} <th class="align-middle" style="width: 20%" scope="row">{{forloop.counter}}</th> {% endcomment %}
        <td style="align-middle" style="width: 10%">{{news.category}}</td>
        <td class="align-middle" style="width: 30%"><a href = {{news.link}}>{{news.title}}</td>
        <td class="align-middle" style="width: 40%">{{news.tag}}</td>
        <td style="align-middle" style="width: 5%">{{news.date}}</td>


        {% comment %} <td class="align-middle" style="width: 20%">{{}}</td> {% endcomment %}
          {% comment %} <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal{{customer.pk}}">스터디메이트 요청</a> {% endcomment %}
        {% comment %} </td> {% endcomment %}
      </tr>       
      {% endfor %}
    </tbody>
  </table>
  {% if news_num > page %}
  <form action="{% url 'newsletter:economy' %}" method = 'POST'>
  {% csrf_token %}
    <input type="hidden" value="{{page}}" name='page' readonly/>
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">더 보기 ({{economy_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  </form>
  {% else %}
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">끝 페이지 ({{economy_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  {% endif %}
{% endblock %}

AI팀메이트/ai_teammate/newsletter/templates/newsletter_health.html
{% extends "base.html" %}

{% block title %}
<title>뉴스레터 - 건강</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:all' %}">공통</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:art' %}">문화/예술</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:economy' %}">경제</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:health' %}" style="color:white;">건강</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:social' %}">사회</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:tech' %}">기술</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <table class="table">
    <thead class="table-light text-center">
      <tr>
        <th style="width: 10%" scope="col">카테고리</th>
        <th style="width: 30%" scope="col">뉴스 제목</th>
        <th style="width: 40%" scope="col">태그</th>
        <th style="width: 5%" scope="col">날짜</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for news in health_list %}
       <tr>
        {% comment %} <th class="align-middle" style="width: 20%" scope="row">{{forloop.counter}}</th> {% endcomment %}
        <td style="align-middle" style="width: 10%">{{news.category}}</td>
        <td class="align-middle" style="width: 30%"><a href = {{news.link}}>{{news.title}}</td>
        <td class="align-middle" style="width: 40%">{{news.tag}}</td>
        <td style="align-middle" style="width: 5%">{{news.date}}</td>


        {% comment %} <td class="align-middle" style="width: 20%">{{}}</td> {% endcomment %}
          {% comment %} <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal{{customer.pk}}">스터디메이트 요청</a> {% endcomment %}
        {% comment %} </td> {% endcomment %}
      </tr>       
      {% endfor %}
    </tbody>
  </table>
  {% if news_num > page %}
  <form action="{% url 'newsletter:health' %}" method = 'POST'>
  {% csrf_token %}
    <input type="hidden" value="{{page}}" name='page' readonly/>
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">더 보기 ({{health_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  </form>
  {% else %}
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">끝 페이지 ({{health_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  {% endif %}
{% endblock %}

AI팀메이트/ai_teammate/newsletter/templates/newsletter_social.html
{% extends "base.html" %}

{% block title %}
<title>뉴스레터 - 사회</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:all' %}">공통</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:art' %}">문화/예술</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:economy' %}">경제</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:health' %}">건강</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:social' %}" style="color:white;">사회</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'newsletter:tech' %}">기술</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <table class="table">
    <thead class="table-light text-center">
      <tr>
        <th style="width: 10%" scope="col">카테고리</th>
        <th style="width: 30%" scope="col">뉴스 제목</th>
        <th style="width: 40%" scope="col">태그</th>
        <th style="width: 5%" scope="col">날짜</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for news in social_list %}
       <tr>
        {% comment %} <th class="align-middle" style="width: 20%" scope="row">{{forloop.counter}}</th> {% endcomment %}
        <td style="align-middle" style="width: 10%">{{news.category}}</td>
        <td class="align-middle" style="width: 30%"><a href = {{news.link}}>{{news.title}}</td>
        <td class="align-middle" style="width: 40%">{{news.tag}}</td>
        <td style="align-middle" style="width: 5%">{{news.date}}</td>


        {% comment %} <td class="align-middle" style="width: 20%">{{}}</td> {% endcomment %}
          {% comment %} <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal{{customer.pk}}">스터디메이트 요청</a> {% endcomment %}
        {% comment %} </td> {% endcomment %}
      </tr>       
      {% endfor %}
    </tbody>
  </table>
  {% if news_num > page %}
  <form action="{% url 'newsletter:social' %}" method = 'POST'>
  {% csrf_token %}
    <input type="hidden" value="{{page}}" name='page' readonly/>
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">더 보기 ({{social_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  </form>
  {% else %}
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">끝 페이지 ({{social_list|length|add:page|add:"-10"}}/{{ news_num }})</button>
  {% endif %}
{% endblock %}