인공지능 서비스 프로젝트/ai_teammate/team_rec/urls.py
from django.urls import path
from . import views

app_name = "team_rec"
urlpatterns = [
    path("choice", views.choice, name="choice"),
    path("person/<int:customer_pk>", views.team_rec_list, name="person"),
    path("team/", views.team, name="team"),
    path("member/<int:customer_pk>", views.member, name="member"),
    path("make/", views.team_make, name="team_make"),
]

인공지능 서비스 프로젝트/ai_teammate/team_rec/templates/team_rec/team_choice.html
{% extends "base.html" %}

{% block title %}
<title>팀메이트 추천</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        {% if user.customer.study.get.study_sum == 10 %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'study_rec:study_rec_list' user.pk %}">studymate</a>
        </li>
        {% else %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'home' %}">studymate</a>
        </li>
        {% endif %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'edit:info_edit' user.customer.pk %}">mypage</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

<br>
<br>
<br>
<br>
<br>
{% comment %} <button type="button" href="{% url 'team_rec:person' user.customer.pk %}">웹통으로 바로이동</button> {% endcomment %}
<form action="{% url 'team_rec:person' user.customer.pk %}">
    <input type="submit" value="개인 추천" />
</form>
<form action="{% url 'team_rec:team' %}">
    <input type="submit" value="팀 추천" />
</form>
<form action="{% url 'team_rec:member' user.customer.pk %}">
    <input type="submit" value="팀원 추천" />
</form>
<form action="{% url 'team_rec:team_make' %}">
    <input type="submit" value="팀 만들기" />
</form>



{% endblock %}

인공지능 서비스 프로젝트/ai_teammate/team_rec/templates/team_rec/team_make.html
{% extends "base.html" %}

{% block title %}
<title>팀메이트 추천</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        {% if user.customer.study.get.study_sum == 10 %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'study_rec:study_rec_list' user.pk %}">studymate</a>
        </li>
        {% else %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'home' %}">studymate</a>
        </li>
        {% endif %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'edit:info_edit' user.customer.pk %}">mypage</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <br>
  <br>

  <h1>팀 만들기</h1>
  <form method="POST" class="team-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default"> Save </button>
  </form>


{% endblock %}

인공지능 서비스 프로젝트/ai_teammate/team_rec/templates/team_rec/team_member.html
{% extends "base.html" %}

{% block title %}
<title>팀메이트 추천</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        {% if user.customer.study.get.study_sum == 10 %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'study_rec:study_rec_list' user.pk %}">studymate</a>
        </li>
        {% else %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'home' %}">studymate</a>
        </li>
        {% endif %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'edit:info_edit' user.customer.pk %}">mypage</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>
  
{% endblock %}

인공지능 서비스 프로젝트/ai_teammate/team_rec/templates/team_rec/team_rec_list.html
{% extends "base.html" %}

{% block title %}
<title>팀메이트 추천</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        {% if user.customer.study.get.study_sum == 10 %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'study_rec:study_rec_list' user.pk %}">studymate</a>
        </li>
        {% else %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'home' %}">studymate</a>
        </li>
        {% endif %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'edit:info_edit' user.customer.pk %}">mypage</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <table class="table">
    <thead class="table-light text-center">
      <tr>
        <th style="width: 10%" scope="col">추천 순위</th>
        <th style="width: 10%" scope="col">이름</th>
        <th style="width: 25%" scope="col">흥미</th>
        <th style="width: 25%" scope="col">선호역할</th>
        <th style="width: 10%" scope="col">팀여부</th>
        <th style="width: 20%" scope="col">신청</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for customer in recommend_customer_list %}
       <tr>
        <th class="align-middle" style="width: 10%" scope="row">{{forloop.counter|add:page|add:"-5"}}</th>
        <td class="align-middle" style="width: 10%">{{customer.name}}</td>
        <td style="width: 25%"><img src="/static/domain_graph_{{customer.pk}}.png" alt="">
        </td>
        {% comment %} <td>{{customer.domain.get.health}} / {{customer.domain.get.economy}} / {{customer.domain.get.culture_art}} / {{customer.domain.get.education}} / {{customer.domain.get.society}} / {{customer.domain.get.technology}}</td> {% endcomment %}
        <td style="width: 25%"><img src="/static/role_graph_{{customer.pk}}.png" alt=""></td>
        <td class="align-middle" style="width: 10%">
        {% if customer.team_state == 0 %}
          ❌
        {% else %}
          ⭕
        {% endif %}
        </td>
        <td class="align-middle" style="width: 20%">
          <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal{{customer.pk}}">팀메이트 요청</a>
        </td>
      </tr>   
        <div class="modal fade" id="exampleModal{{customer.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{customer.name}}님께 팀메이트 요청</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <form action="{% url 'team_rec:person' user.pk %}" method = 'POST'>
              {% csrf_token %}       
              <input type="hidden" value="{{page}}" name='page' readonly/>
              <input type="hidden" value="{{customer.pk}}" name='request' readonly/>           
              <div class="modal-body text-center">
                <p>보내고 싶은 메세지를 입력하세요!</p>
                <p>(자기소개, 연락처 등)</p>
                <textarea name='contents' style="width:100%; height:15vh;"></textarea>
              </div>
              <div class="modal-footer">               
                <button type="submit" class="btn btn-outline-primary">요청 보내기</button>
              </div>
              </form>
            </div>
          </div>
        </div>  
      {% endfor %}
    </tbody>
  </table>
  {% if recommend_customer_length > page %}
  <form action="{% url 'team_rec:person' user.pk %}" method = 'POST'>
  {% csrf_token %}
    <input type="hidden" value="{{page}}" name='page' readonly/>
    <input type="hidden" value="0" name='request' readonly/>
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">더 보기 ({{recommend_customer_list|length|add:page|add:"-5"}}/{{ recommend_customer_length }})</button>
  </form>
  {% else %}
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">끝 페이지 ({{recommend_customer_list|length|add:page|add:"-5"}}/{{ recommend_customer_length }})</button>
  {% endif %}
{% endblock %}

인공지능 서비스 프로젝트/ai_teammate/team_rec/templates/team_rec/team_team.html
{% extends "base.html" %}

{% block title %}
<title>팀메이트 추천</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        {% if user.customer.study.get.study_sum == 10 %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'study_rec:study_rec_list' user.pk %}">studymate</a>
        </li>
        {% else %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'home' %}">studymate</a>
        </li>
        {% endif %}
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'edit:info_edit' user.customer.pk %}">mypage</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <table class="table">
    <thead class="table-light text-center">
      <tr>
        {% comment %} <th style="width: 5%" scope="col">추천 순위</th> {% endcomment %}
        <th style="width: 10%" scope="col">팀명</th>
        <th style="width: 15%" scope="col">팀 소개</th>
        <th style="width: 10%" scope="col">팀장</th>
        <th style="width: 10%" scope="col">마감</th>
        <th style="width: 10%" scope="col">신청</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for team in all_list %}
       <tr>
        {% comment %} <th class="align-middle" style="width: 20%" scope="row">{{forloop.counter}}</th> {% endcomment %}
        <td style="align-middle" style="width: 10%">{{team.name}}</td>
        <td class="align-middle" style="width: 15%">{{team.intro}}</td>
        <td class="align-middle" style="width: 10%">{{team.leader}}</td>
        <td style="align-middle" style="width: 10%">{{team.state}}</td>



        {% comment %} <td class="align-middle" style="width: 20%">{{}}</td> {% endcomment %}
          {% comment %} <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal{{customer.pk}}">스터디메이트 요청</a> {% endcomment %}
        {% comment %} </td> {% endcomment %}
      </tr>       
      {% endfor %}
    </tbody>
  </table>

{% endblock %}