AI팀메이트/ai_teammate/ai_teammate/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('users/', include('users.urls')),
    path('edit/', include('edit.urls')),
    path('alarm/', include('alarm.urls')),
    path('team_rec/', include('team_rec.urls')),
    path('study_rec/', include('study_rec.urls')),
    path('newsletter/',include('newsletter.urls')),
]

AI팀메이트/ai_teammate/alarm/urls.py
from django.urls import path
from . import views

app_name = "alarm"
urlpatterns = [
    path('alarm_list/<int:customer_pk>', views.alarm_list, name='alarm_list'),
    path('alarm_create/<int:customer_pk>', views.alarm_create, name='alarm_create'),
    path('del_alarm/<int:message_pk>', views.del_alarm, name='del_alarm'),
    path('check_info/<int:message_pk>', views.check_info, name='check_info'),
    path('alarm_create2/<int:customer_pk>', views.alarm_create2, name='alarm_create2'),
    path('del_alarm2/<int:message_pk>', views.del_alarm2, name='del_alarm2'),
    path('check_info2/<int:message_pk>', views.check_info2, name='check_info2'), 
]

AI팀메이트/ai_teammate/edit/urls.py
from django.urls import path
from . import views

app_name = "edit"
urlpatterns = [
    path("info_edit/<int:customer_pk>", views.info_edit, name="info_edit"),  # 정보수정하기
    path(
        "domain_edit/<int:customer_pk>", views.domain_edit, name="domain_edit"
    ),  # 흥미 설문조사 정보수정
    path(
        "score_edit/<int:customer_pk>", views.score_edit, name="score_edit"
    ),  # 실력 설문조사 정보수정
    path(
        "role_edit/<int:customer_pk>", views.role_edit, name="role_edit"
    ),  # 흥미 설문조사 정보수정
    path(
        "study_edit/<int:customer_pk>", views.study_edit, name="study_edit"
    ),  # 흥미 설문조사 정보수정
]

AI팀메이트/ai_teammate/study_rec/urls.py
from django.urls import path
from . import views

app_name = "study_rec"
urlpatterns = [
    path(
        "study_rec_list/<int:customer_pk>", views.study_rec_list, name="study_rec_list"
    ),
]

AI팀메이트/ai_teammate/team_rec/urls.py
from django.urls import path
from . import views

app_name = "team_rec"
urlpatterns = [
    path("team_rec_list/<int:customer_pk>", views.team_rec_list, name="team_rec_list"),
]

AI팀메이트/ai_teammate/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("signup2/<int:customer_pk>", views.signup2, name="signup2"),
    path("signup3/<int:customer_pk>", views.signup3, name="signup3"),
    path("signup4/<int:customer_pk>", views.signup4, name="signup4"),
    path("signup5/<int:customer_pk>", views.signup5, name="signup5"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

AI팀메이트/ai_teammate/study_rec/models.py
from django.db import models

# Create your models here.

AI팀메이트/ai_teammate/study_rec/views.py
from django.shortcuts import render
from users.models import Customer, Domain, Score, Role, Study
from django.contrib import auth
from sklearn.metrics.pairwise import cosine_similarity
from django_pandas.io import read_frame
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc("font", family=font_name)

###############################################################


def get_not_zero_hope_course(input_num, customer_study):
    # 스터디 과목중 하트를 하나라도 준 과목들 리스트 리턴하는 함수
    return customer_study.loc[input_num][
        customer_study.loc[input_num] != 0
    ].index.tolist()


def course_to_ability(course_list):
    # 스터디 과목 리스트를 받아 그에 맞는 성적으로 매칭, 리스트로 정리해 리턴하는 함수
    ablility = []
    for course in course_list:
        if course in [
            "voice_recog_hearts",
            "computer_vision_hearts",
            "rec_system_hearts",
            "reinforcement_hearts",
        ]:
            if "modeling_score" not in ablility:
                ablility.append("modeling_score")
        elif course == "basic_python_hearts":
            if "mean" not in ablility:
                ablility.append("mean")
        elif course == "data_analysis_hearts":
            if "data_score" not in ablility:
                ablility.append("data_score")
        else:
            if course not in ablility:
                ablility.append(course[:-7])
    return ablility


def get_grade_for_hope_course(input_num, customer_study, customer_score):
    # 사용자 번호를 받아 해당 사용자가 하트를 준 스터디과목만 골라
    # 전체 사용자의 해당 과목 성적을 리턴하는 함수
    necessary_ability_list = course_to_ability(
        get_not_zero_hope_course(input_num, customer_study)
    )
    return customer_score[necessary_ability_list]


def get_grade_sub_for_hope_course(input_num, customer_study, customer_score):
    # 사용자 번호를 받아 해당 사용자가 하트를 준 스터디과목만 골라 정리하고
    # 전체성적에서 사용자의 성적을 뺀 절대값을 리턴하는 함수
    hope_course = get_grade_for_hope_course(input_num, customer_study, customer_score)
    grade_sub_only_hope_course = np.abs(hope_course - hope_course.loc[input_num]).mean(
        axis=1
    )
    return grade_sub_only_hope_course


###############################################################

# 스터디메이트 추천시스템
def study_rec_list(request, customer_pk):
    page = 5
    if request.method == "POST":
        page = int(request.POST["page"]) + 5

    customer_list = Customer.objects.all()
    score_list = Score.objects.all()
    study_list = Study.objects.all()
    df0 = read_frame(customer_list)
    df1 = read_frame(score_list)
    df2 = read_frame(study_list)
    customer_score = df1.loc[
        :,
        [
            "web",
            "design",
            "data_score",
            "modeling_score",
            "machine_learning",
            "statistics",
            "deep_learning",
            "algorithm",
            "nlp",
        ],
    ]

    customer_score_sum = customer_score.sum(axis=1)
    customer_score["mean"] = customer_score.mean(axis=1)
    customer_study = df2.loc[
        :,
        [
            "web_hearts",
            "design_hearts",
            "machine_learning_hearts",
            "statistics_hearts",
            "deep_learning_hearts",
            "algorithm_hearts",
            "nlp_hearts",
            "basic_python_hearts",
            "data_analysis_hearts",
            "voice_recog_hearts",
            "computer_vision_hearts",
            "rec_system_hearts",
            "reinforcement_hearts",
        ],
    ]

    my_num = df0[df0["user"] == customer_pk].index.tolist()[0]
    # 만약에 전부 0점이라 과목이 없으면 오류뜸. 처리필요!
    study_similarity = cosine_similarity(customer_study, customer_study)
    hope_course_score = get_grade_for_hope_course(
        my_num, customer_study, customer_score
    )
    grade_subs = (
        get_grade_sub_for_hope_course(my_num, customer_study, customer_score) * 0.1
    )
    score_similarity = cosine_similarity(hope_course_score, hope_course_score)
    evaluation_value = (
        grade_subs - study_similarity[my_num - 1] - score_similarity[my_num - 1]
    )

    recommend_id_list = evaluation_value.sort_values().index.tolist()

    if my_num in recommend_id_list:
        recommend_id_list.remove(my_num)
    recommend_pk_list = df0.iloc[recommend_id_list].id

    recommend_customer_list = []
    recommend_customer_list_already = []
    recommend_customer_length = len(recommend_pk_list)
    if len(recommend_pk_list) <= 5:
        recommend_pk_list = recommend_pk_list
    elif len(recommend_pk_list) <= page:
        recommend_pk_list = recommend_pk_list[page - 5 :]
    else:
        recommend_pk_list = recommend_pk_list[page - 5 : page]

    for i in recommend_pk_list:
        now_customer = Customer.objects.get(pk=int(i))
        if now_customer.study_state == 1:
            recommend_customer_list_already.append(now_customer)
        else:
            recommend_customer_list.append(now_customer)

        study_index = [
            "웹",
            "디자인",
            "머신러닝",
            "통계",
            "딥러닝",
            "알고리즘",
            "NLP",
            "파이썬",
            "데이터",
            "음성인식",
            "비전",
            "추천",
            "강화학습",
        ]
        study_values = [
            Study.objects.get(foreignkey=now_customer).web_hearts,
            Study.objects.get(foreignkey=now_customer).design_hearts,
            Study.objects.get(foreignkey=now_customer).machine_learning_hearts,
            Study.objects.get(foreignkey=now_customer).statistics_hearts,
            Study.objects.get(foreignkey=now_customer).deep_learning_hearts,
            Study.objects.get(foreignkey=now_customer).algorithm_hearts,
            Study.objects.get(foreignkey=now_customer).nlp_hearts,
            Study.objects.get(foreignkey=now_customer).basic_python_hearts,
            Study.objects.get(foreignkey=now_customer).data_analysis_hearts,
            Study.objects.get(foreignkey=now_customer).voice_recog_hearts,
            Study.objects.get(foreignkey=now_customer).computer_vision_hearts,
            Study.objects.get(foreignkey=now_customer).rec_system_hearts,
            Study.objects.get(foreignkey=now_customer).reinforcement_hearts,
        ]
        color = [
            "#F78181",
            "#F79F81",
            "#F7BE81",
            "#F5DA81",
            "#F3F781",
            "#D8F781",
            "#9FF781",
            "#81F79F",
            "#A9E2F3",
            "#A9E2F3",
            "#D0A9F5",
            "#F5A9F2",
            "#F781BE",
        ]
        study_index_after = []
        study_values_after = []
        color_after = []
        for j in range(0, 13):
            if int(study_values[j]) > 0:
                study_index_after.append(study_index[j])
                study_values_after.append(study_values[j])
                color_after.append(color[j])
        print(study_index_after)
        plt.figure(figsize=(3, 3))
        plt.xticks(fontsize=8)
        plt.bar(
            study_index_after,
            study_values_after,
            color=color_after,
            width=0.5,  # default: 0.8
        )
        plt.savefig(f"./static/study_graph_{i}.png")
    recommend_customer_list = recommend_customer_list + recommend_customer_list_already
    context = {
        "recommend_customer_list": recommend_customer_list,
        "page": page,
        "recommend_customer_length": recommend_customer_length,
    }

    return render(request, "study_rec/study_rec_list.html", context)

AI팀메이트/ai_teammate/study_rec/templates/study_rec/study_rec_list.html
{% extends "base.html" %}

{% block title %}
<title>스터디메이트 추천</title>
{% endblock %}

{% block style %}
<!--이 곳에 style에 해당하는 코드 (css파일 연결 등) 작성-->
{% endblock %}

{% block content %}
<!--이 곳에 페이지의 내용 작성-->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#ffbbb1;">
    <a class="navbar-brand" href="{% url 'home' %}" >Home</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'team_rec:team_rec_list' user.pk %}">teammate</a>
        </li>
        <li class="nav-item justify-content-end">
          <a class="nav-link" href="{% url 'edit:info_edit' user.customer.pk %}">mypage</a>
        </li>
      </ul>
      <a class="nav-link my-2 my-sm-0" style="color:white;" href="{% url 'users:logout' %}">signout</a>
    </div>
  </nav>

  <br>
  <br>
  <table class="table">
    <thead class="table-light text-center">
      <tr>
        <th style="width: 20%" scope="col">추천 순위</th>
        <th style="width: 20%" scope="col">이름</th>
        <th style="width: 30%" scope="col">스터디선호도</th>
        <th style="width: 10%" scope="col">스터디여부</th>
        <th style="width: 20%" scope="col">신청</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for customer in recommend_customer_list %}
      <div class="modal fade" id="exampleModal{{customer.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">{{customer.name}}님께 스터디메이트 요청</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="{% url 'alarm:alarm_create2' customer.pk %}" method = 'POST'>
            {% csrf_token %}                
            <div class="modal-body text-center">
              <p>보내고 싶은 메세지를 입력하세요!</p>
              <p>(자기소개, 연락처 등)</p>
              <textarea name='contents' style="width:100%; height:15vh;"></textarea>
            </div>
            <div class="modal-footer">               
              <button type="submit" class="btn btn-outline-primary">요청 보내기</button>
            </div>
            </form>
          </div>
        </div>
      </div>
       <tr>
        <th class="align-middle" style="width: 20%" scope="row">{{forloop.counter}}</th>
        <td class="align-middle" style="width: 20%">{{customer.name}}</td>
        <td style="width: 30%"><img src="/static/study_graph_{{customer.pk}}.png" alt=""></td>
        <td class="align-middle" style="width: 10%">{{customer.study_state}}</td>
        <td class="align-middle" style="width: 20%">
          <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal{{customer.pk}}">스터디메이트 요청</a>
        </td>
      </tr>  
      {% endfor %}
    </tbody>
  </table>
  {% if recommend_customer_length > page %}
  <form action="{% url 'team_rec:team_rec_list' user.pk %}" method = 'POST'>
  {% csrf_token %}
    <input type="hidden" value="{{page}}" name='page' readonly/>
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">더 보기 ({{recommend_customer_list|length|add:page|add:"-5"}}/{{ recommend_customer_length }})</button>
  </form>
  {% else %}
    <button type="submit" class="btn btn-outline-info btn-lg btn-block">끝 페이지 ({{recommend_customer_list|length|add:page|add:"-5"}}/{{ recommend_customer_length }})</button>
  {% endif %}
{% endblock %}